name: nscc_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.3
  flutter_secure_storage: ^7.0.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  lottie: ^2.2.0
  get: ^4.6.5
  http:
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black-900.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold-800.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold-700.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold-600.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium-500.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light-300.ttf
          weight: 300        
        - asset: assets/fonts/Poppins/Poppins-ExtraLight-200.ttf
          weight: 200                   
        - asset: assets/fonts/Poppins/Poppins-Thin-100.ttf
          weight: 100
 
